RiddleCompass_Riddles_Alliance = {
    ["Arcane power thrums. Journey home with a mere step. Dig beside the roost."] = { mapID = 16105, x = 56.65, y = 27.51, hint = "" },
    ["Sentinel of Stone. First to greet each new neighbor. Seek out the deep shade."] = { mapID = 16105, x = 58.13, y = 30.08, hint = "" },
    ["Lush trees grow skyward. A stream threads through leafy glades. Look where waters churn."] = { mapID = 16105, x = 49.72, y = 42.42, hint = "" },
    ["Cool waters unfed. Still against blue sky and green. Sheltered by the cliff."] = { mapID = 16105, x = 49.18, y = 27.13, hint = "" },
    ["Covered connection. Over the lilied waters. Search the banks below."] = { mapID = 16105, x = 42.47, y = 44.76, hint = "" },
    ["Where trees have no roots. A gate has no door or hinge. Will call for treasure."] = { mapID = 16105, x = 55.34, y = 39.96, hint = "" },
    ["Azure and gold sway. While beneath pretenders play. Investigate stage left."] = { mapID = 16105, x = 57.34, y = 39.26, hint = "" },
    ["Where roses are red. The perfect venue waits. Throw some rice, then dig."] = { mapID = 16105, x = 57.81, y = 42.04, hint = "" },
    ["Earth, fire, smoke, and steam. Blade or plow, the shaper’s choice. Look where metals bend."] = { mapID = 16105, x = 53.65, y = 39.79, hint = "" },
    ["Seek the smallest house. Where pawsteps mark the sand. Now dig where dogs lie."] = { mapID = 16105, x = 53.60, y = 41.94, hint = "" },
    ["Six sides, but no walls. Afloat above chill waters. Secrets wait below."] = { mapID = 16105, x = 52.44, y = 28.80, hint = "" },
    ["Mushrooms mark the ring. Deep within the shadowed wood. Dig where fireflies swarm."] = { mapID = 16105, x = 60.31, y = 56.82, hint = "" },
    ["Fireflies glow and flit. Falls feed the whispering wood. The drowned cave awaits."] = { mapID = 16105, x = 66.88, y = 57.02, hint = "" },
    ["Near the twilit wood. Falls give a cave’s mouth its roar. Look beneath a torch."] = { mapID = 16105, x = 59.24, y = 44.93, hint = "" },
    ["Aboveground tunnel. Lights mark where life’s blood once flowed. Look atop the falls."] = { mapID = 16105, x = 55.05, y = 50.71, hint = "" },
    ["Names worn down by time. Stone weeps where the water sings. Drop a coin, then dig."] = { mapID = 16105, x = 58.34, y = 65.04, hint = "" },
    ["Tribute to the lost. Where seaspray climbs ancient cliffs. A lonely bell tolls."] = { mapID = 16105, x = 55.41, y = 71.50, hint = "" },
    ["Cart lost in the dark. Growth consumes all that remains. Search beside the road."] = { mapID = 16105, x = 56.82, y = 52.29, hint = "" },
    ["Pale moonlight rises. Wisps guard what the dusk holds dear. Look where roots rise up."] = { mapID = 16105, x = 49.89, y = 56.61, hint = "" },
    ["No leaves, yet it blooms. Still limbs cradle gentle glows. Wade where violet grows."] = { mapID = 16105, x = 59.59, y = 52.44, hint = "" },
    ["Trellis frames the Torch. A seat above misty shores. Seek the ledge below."] = { mapID = 16105, x = 52.82, y = 66.83, hint = "" },
    ["Awnings span river’s flow. Gold to the west, darkness east. Look beneath stunted tree."] = { mapID = 16105, x = 47.69, y = 61.97, hint = "" },
    ["Beyond smugglers cove. Wrecks hide a sunken saloon. Look for the good stuff."] = { mapID = 16105, x = 61.88, y = 82.54, hint = "" },
    ["Salt clings to old wood. Crow’s nests watch the tide retreat. A cave holds secrets."] = { mapID = 16105, x = 61.61, y = 79.44, hint = "" },
    ["Across from the bight. The oyster shuckers have gone. Search the lonely dock."] = { mapID = 16105, x = 64.56, y = 85.59, hint = "" },
    ["A weary roof sighs. Ships rot just beyond the reach. Look beneath the bow."] = { mapID = 16105, x = 54.18, y = 73.63, hint = "" },
    ["Water Flows Below. While fresh cider flows above. Dig where the wheel churns."] = { mapID = 16105, x = 46.32, y = 57.97, hint = "" },
    ["Harvest hangs from boughs. Crimson against autumn gold. Trust the lantern’s light."] = { mapID = 16105, x = 36.60, y = 54.12, hint = "" },
    ["Light sweeps open sea. A beacon upon the bluff. Look behind its back."] = { mapID = 16105, x = 33.99, y = 72.68, hint = "" },
    ["Blades turn in the wind. Amber leaves drift toward the sea. Check beneath the stairs."] = { mapID = 16105, x = 34.61, y = 60.43, hint = "" },
    ["Beneath gryphon’s wings. On the small aerie’s low slopes. Find the broken tree."] = { mapID = 16105, x = 42.69, y = 53.92, hint = "" },
    ["Small farmer’s homestead. Where cows bask in golden light. Dig between the rows."] = { mapID = 16105, x = 39.10, y = 59.95, hint = "" },
    ["Cows low in their pen. Leaves fall on the roundabout. Treasure waits within."] = { mapID = 16105, x = 40.85, y = 61.31, hint = "" },
    ["Below autumn soil. Gargled seaweed and dead fish. Stone mouth drinks the sea."] = { mapID = 16105, x = 45.42, y = 64.34, hint = "" },
    ["Hollow nurse log yawns. Waters reflect gold above. Dry leaves hide riches."] = { mapID = 16105, x = 36.61, y = 57.85, hint = "" },
    ["Petals sway in the breeze. Wooden arms sweep floral scents. Look where pink meets gold."] = { mapID = 16105, x = 36.92, y = 32.93, hint = "" },
    ["Twin silos stand watch. Meandering rows slumber. Search among the rocks."] = { mapID = 16105, x = 39.95, y = 31.95, hint = "" },
    ["Vines climb the hillside. Their yield crushed in tubs of wood. Look where juice stains earth."] = { mapID = 16105, x = 41.00, y = 28.37, hint = "" },
    ["Stairs snake up the bluffs. A pier juts over shallows. Seek the shade below."] = { mapID = 16105, x = 29.04, y = 28.17, hint = "" },
    ["Prism of the cove. Where worn stone endures the roar. Dive deep to prevail."] = { mapID = 16105, x = 37.09, y = 45.92, hint = "" },
    ["Watcher on the shore. Where ships drop anchor and make berth. Look where crabs scuttle."] = { mapID = 16105, x = 29.85, y = 48.32, hint = "" },
    ["Gulls scream for free meals. Salt clings to fingermonger scales. Seek the barnacles."] = { mapID = 16105, x = 28.62, y = 46.71, hint = "" },
    ["Boardwalk lies broken. Sand bars cradle what remains. Seek out the lone plank."] = { mapID = 16105, x = 28.33, y = 40.14, hint = "" },
    ["A lone flag flutters. Covered bridge over dry ground. Sift the sand beneath."] = { mapID = 16105, x = 30.86, y = 31.12, hint = "" },
    ["Outside outer banks. Where crabs claim an island shore. Sift through the driftwood."] = { mapID = 16105, x = 21.12, y = 30.06, hint = "" },
    ["An old flag flutters. A platform grants ocean views. Look below the stairs."] = { mapID = 16105, x = 26.20, y = 37.91, hint = "" },
    ["Stone laid by lost hands. Bridging the mountain runoff. Look where lilies listen."] = { mapID = 16105, x = 62.23, y = 38.30, hint = "" },
    ["Highland rime meets mists. Gateway to the dusky wood. The dead point the way."] = { mapID = 16105, x = 63.12, y = 46.74, hint = "" },
    ["Mountain guardian. Dark forest whispers below. Look to the lone pine."] = { mapID = 16105, x = 64.87, y = 50.99, hint = "" },
    ["Clouds bow to the stone. Heights where gryphons dare not fly. Above all, it waits."] = { mapID = 16105, x = 69.21, y = 26.71, hint = "" },
}