RiddleCompass_Riddles_Horde = {
    ["Between mighty tusks. A doorway shimmers and hums. Look where the carts park."] = { mapID = 15524, x = 53.73, y = 50.22, hint = "" },
    ["Where kodos take rest. Past gate marked with bone and fire. Dig near hay bale."] = { mapID = 15524, x = 57.15, y = 58.27, hint = "" },
    ["Two towers stand guard. Worn bridge spans the falls below. Go smell some flowers."] = { mapID = 15524, x = 55.59, y = 49.79, hint = "" },
    ["Below the towers. Townsfolk guarded from the spray. Dig in awning’s shade."] = { mapID = 15524, x = 55.57, y = 52.40, hint = "" },
    ["Though it may have leaks. Wooden wall diverts the stream. Check the ledge below."] = { mapID = 15524, x = 56.40, y = 48.02, hint = "" },
    ["Near where farmers toil. Beast of burden raises young. Seek the broadest shade."] = { mapID = 15524, x = 50.96, y = 61.56, hint = "" },
    ["Penned in desert bloom. Loyal steeds water and feed. Needles in haystacks."] = { mapID = 15524, x = 59.05, y = 73.66, hint = "" },
    ["Through an arch of bone. A stream cradles what once moved. Search the vertebrae."] = { mapID = 15524, x = 60.72, y = 64.50, hint = "" },
    ["Three huts in spire’s shade. Wooden overlook curves out front. Search near a planter"] = { mapID = 15524, x = 64.53, y = 69.21, hint = "" },
    ["Life stirs from dry soil. Camp where fishers may take rest. Fire warms the treasure."] = { mapID = 15524, x = 58.66, y = 69.49, hint = "" },
    ["Where the desert blooms. Fire burns at circle’s center. Look to the shadows."] = { mapID = 15524, x = 57.76, y = 63.45, hint = "" },
    ["Mist threads through the pines. Sellers ring the roundabout. Search the succulents."] = { mapID = 15524, x = 63.88, y = 51.80, hint = "" },
    ["Three falls feed the flows. Fishers hunt with spear and trap. Look below the traps."] = { mapID = 15524, x = 63.60, y = 44.81, hint = "" },
    ["Below forest deck. Secret straw-floored writer’s nook. Seek the wheelbarrow."] = { mapID = 15524, x = 63.73, y = 56.23, hint = "" },
    ["From a sagging rope bridge. Torches mark a steep descent. Search the water’s edge."] = { mapID = 15524, x = 70.29, y = 49.80, hint = "" },
    ["Cedar scents the air. Where kneaded muscles soak deep. Search between tubs."] = { mapID = 15524, x = 68.93, y = 52.48, hint = "" },
    ["Platform high above. At the edge of sea and wood. Look where the lights sway."] = { mapID = 15524, x = 72.12, y = 41.65, hint = "" },
    ["Six tables are dressed. Conifers observe the feast. Compliment the chef."] = { mapID = 15524, x = 62.29, y = 48.90, hint = "" },
    ["Back steps to the wood. Above needled canopy. Stop halfway and search."] = { mapID = 15524, x = 57.99, y = 48.91, hint = "" },
    ["Deep in the forest. Where the hookah haze rises. Treasure waits below."] = { mapID = 15524, x = 64.65, y = 58.04, hint = "" },
    ["Steam bursts toward the sky. Blue pools swirl with ancient heat. Look for the tether."] = { mapID = 15524, x = 51.96, y = 74.96, hint = "" },
    ["From atop the falls. Stargazers peer past the palms. Dig through their notes."] = { mapID = 15524, x = 44.80, y = 56.96, hint = "" },
    ["Where clear waters churn. The earth opens wide to breathe. What waits in its maw?"] = { mapID = 15524, x = 45.55, y = 56.94, hint = "" },
    ["Oasis Watcher Perched above crystal waters. Find the bench below."] = { mapID = 15524, x = 41.39, y = 67.95, hint = "" },
    ["Old watering hole. Take a swing or take a dive. Hold your breath and dig."] = { mapID = 15524, x = 42.63, y = 50.39, hint = "" },
    ["Overlooking fields. Bushels brim with bloom and seed. Check for stock in back."] = { mapID = 15524, x = 49.54, y = 60.04, hint = "" },
    ["Oasis bears fruit. Seek not the greens, but purple. Harvest at center."] = { mapID = 15524, x = 47.18, y = 59.70, hint = "" },
    ["Where palm trees grow thick. Platform sits on stone’s old spine. Look to the low flame."] = { mapID = 15524, x = 44.75, y = 66.36, hint = "" },
    ["Across gentle falls. Bridge broken, chains given way. Look to the east end."] = { mapID = 15524, x = 43.25, y = 69.44, hint = "" },
    ["A secret beast den. Hidden behind narrow falls. Search the oasis."] = { mapID = 15524, x = 39.34, y = 57.61, hint = "" },
    ["Wooden mask tends bar. Pineapples lift the spirits. Dig near the fire pit."] = { mapID = 15524, x = 57.93, y = 86.28, hint = "" },
    ["Near the scorching songs. Arbor frames the setting sun. Dig beyond the vows."] = { mapID = 15524, x = 38.65, y = 80.26, hint = "" },
    ["The fire never ends. Gather for sorrow or mirth. Search behind the fuel."] = { mapID = 15524, x = 40.03, y = 78.51, hint = "" },
    ["Stone mouth, wooden teeth. Mast as toothpick, should it eat. Go down its gullet."] = { mapID = 15524, x = 39.51, y = 70.14, hint = "" },
    ["Smugglers scheme above. Tortollans tend bar below. Search through the seaweed."] = { mapID = 15524, x = 39.24, y = 74.01, hint = "" },
    ["Oceanside Ravine. Pirate camp awaits above. Anchor marks the spot."] = { mapID = 15524, x = 50.39, y = 83.02, hint = "" },
    ["Hot air fills the canvas. Where boardwalk crowns stoney arch. Look where the paths cross."] = { mapID = 15524, x = 52.17, y = 81.77, hint = "" },
    ["Highest wyvern perch. Circling above the sea. Look to the center."] = { mapID = 15524, x = 50.97, y = 89.63, hint = "" },
    ["Down below the bluffs. Water flows below stone bridge. Dive to the shipwreck."] = { mapID = 15524, x = 51.73, y = 80.05, hint = "" },
    ["Just like Thunder Bluff. Tower watches three swaying paths. Look to the platform."] = { mapID = 15524, x = 50.36, y = 76.80, hint = "" },
    ["Salt and sea collide. Tower guards the fisher’s catch. Dig at the front steps."] = { mapID = 15524, x = 53.80, y = 88.12, hint = "" },
    ["Seagulls await ships. Tower watches, fountain spits. Look where wyverns perch."] = { mapID = 15524, x = 68.17, y = 75.74, hint = "" },
    ["Wave-swept sandy knoll. Follow the bridge to nowhere. Dig among the palms."] = { mapID = 15524, x = 68.25, y = 68.95, hint = "" },
    ["Seek the bone tunnel. In sight of a broken hull. Trace the sunken chain."] = { mapID = 15524, x = 47.77, y = 88.39, hint = "" },
    ["Dead hulk in the tide. A mast lies against the dunes. The crow’s nest sees all."] = { mapID = 15524, x = 44.22, y = 86.76, hint = "" },
    ["One boardwalk above. A second boardwalk below. Search near the canoes."] = { mapID = 15524, x = 64.81, y = 73.04, hint = "" },
    ["Nature carved a gate. Sea and sand mingle below. Search atop the arch."] = { mapID = 15524, x = 61.87, y = 78.66, hint = "" },
    ["Sea’s greatest hunter. Hanging in the salted air. Search below the deck."] = { mapID = 15524, x = 53.80, y = 82.05, hint = "" },
    ["Boasting two bridges. Isle’s lone palm leans toward the shore. Search the coconuts."] = { mapID = 15524, x = 58.01, y = 79.95, hint = "" },
    ["Two huts crowd the isle. Beach grass sways in the sea breeze. Swim with the starfish."] = { mapID = 15524, x = 62.04, y = 88.70, hint = "" },
}